apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: openshift-gitops-installed
spec:
  remediationAction: enforce
  severity: low
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: openshift-gitops-operator
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: openshift-gitops-operator
          namespace: openshift-gitops-operator
        spec:
          name: openshift-gitops-operator
          channel: stable
          source: redhat-operators
          sourceNamespace: openshift-marketplace

