apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: kubeadmin-removed
spec:
  remediationAction: enforce
  severity: low
  object-templates:
    - complianceType: mustnothave
      objectDefinition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: kubeadmin
          namespace: kube-system
        type: Opaque

